[[language]]
name = "python"
language-servers = [ "ty", "ruff" ]
auto-format = true

[language-server.ty]
command = "ty"
args = ["server"]

[language-server.ruff]
command = "ruff"
args = ["server"]

[[language]]
name = "javascript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "typescript"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true

[[language]]
name = "tsx"
formatter = { command = "npx", args = ["prettier", "--parser", "typescript"] }
auto-format = true
